//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 游戏发布站.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gameEntities : DbContext
    {
        public gameEntities()
            : base("name=gameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdType> AdType { get; set; }
        public DbSet<GameList> GameList { get; set; }
        public DbSet<Navigation> Navigation { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<AdList> AdList { get; set; }
        public DbSet<Config> Config { get; set; }
    }
}
