//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace 游戏发布站.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public string id { get; set; }
        [DisplayName("用 户 名:")]
        public string username { get; set; }
        [DisplayName("密    码:")]
        [Required(ErrorMessage = "{0}不能为空")]
        [StringLength(12, MinimumLength = 6, ErrorMessage = "{0}长度为{2}-{1}位")]
        public string password { get; set; }
        [DisplayName("重复密码:")]
        public string password1 { get; set; }

        [DisplayName("手机号码:")]
        public string mobile { get; set; }
        public string balance { get; set; }
        public string Creation_time { get; set; }
        public string Login_time { get; set; }
        public string Login_nums { get; set; }
    }
}
